@include('comissao.inc.top')
@include('comissao.inc.nav_left')
@include('comissao.inc.nav_menu')
<body>
    @yield('content')
</body>
@include('comissao.inc.footer')
@yield('scripts')
<script>
    @yield('jscripts')
</script>
